name: File Browser
description: |
  filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and each user can have its own directory. It can be used as a standalone app or as a middleware.
version: '0.1'
category: File Managing
maintainer: Brian J. Cardiff <bcardiff@manas.tech>
license: Apache License 2.0
projectURL: https://github.com/filebrowser/filebrowser
